// Copyright (c) 2025 BobLd
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Threading;
using System.Threading.Tasks;
using Caly.Core.Services.Interfaces;
using Caly.Printing.Core;
using SkiaSharp;
using Windows.Win32;
using Windows.Win32.Graphics.Gdi;
using Windows.Win32.Storage.Xps;
using Caly.Core;

namespace Caly.Printing.Windows;

/// <summary>
/// Windows print service.
/// <para>
/// Printer discovery uses the Win32 Print Spooler via CsWin32 (<c>EnumPrinters</c>).
/// Jobs are submitted via the GDI printer-DC path (<c>CreateDC</c> / <c>StartDoc</c> /
/// <c>StartPage</c> / <c>StretchDIBits</c> / <c>EndPage</c> / <c>EndDoc</c> / <c>DeleteDC</c>).
/// </para>
/// </summary>
[SupportedOSPlatform("windows5.0")]
public sealed class WindowsPrintService : IPrintService
{
    public Task<IReadOnlyList<PrinterInfo>> GetAvailablePrintersAsync(CancellationToken token)
    {
        return Task.Run(() => GetWindowsPrintersCore(token), token);
    }

    // Minimal layout for PRINTER_INFO_4W (Level 4 enumeration — fast, local-only).
    // Level 4 is explicitly recommended for printer name enumeration (MSDN).
    // PRINTER_INFO_4W is not generated by CsWin32 due to complex struct dependencies.
    [StructLayout(LayoutKind.Sequential)]
    private unsafe struct PrinterInfo4W
    {
        public char* pPrinterName;
        public char* pServerName;
        public uint  Attributes;
    }

    private static unsafe IReadOnlyList<PrinterInfo> GetWindowsPrintersCore(CancellationToken token)
    {
        Debug.ThrowOnUiThread();

        token.ThrowIfCancellationRequested();

        try
        {
            const uint flags = 0x00000002u | 0x00000004u; // PRINTER_ENUM_LOCAL | PRINTER_ENUM_CONNECTIONS
            const uint level = 4; // PRINTER_INFO_4W — fastest for name enumeration

            // First call: get required buffer size.
            PInvoke.EnumPrinters(flags, null, level, Span<byte>.Empty, out uint needed, out _);
            if (needed == 0)
            {
                return [];
            }

            byte[] buffer = new byte[needed];
            if (!PInvoke.EnumPrinters(flags, null, level, buffer, out _, out uint count))
            {
                return [];
            }

            var result = new List<PrinterInfo>();
            fixed (byte* pBuf = buffer)
            {
                var ptr = (PrinterInfo4W*)pBuf;
                for (uint i = 0; i < count; i++)
                {
                    string? name = ptr[i].pPrinterName is null ? null : new string(ptr[i].pPrinterName);
                    if (!string.IsNullOrWhiteSpace(name))
                    {
                        result.Add(new PrinterInfo(name, null));
                    }
                }
            }

            return result;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"WindowsPrintService: EnumPrinters failed: {ex.Message}");
        }

        return [];
    }

    public Task PrintDocumentAsync(
        PrinterInfo printer,
        IPdfDocumentService documentService,
        IReadOnlyList<PrintPageInfo> pages,
        IProgress<int>? progress,
        CancellationToken token)
    {
        Debug.ThrowOnUiThread();

        return Task.Run(() => PrintWindowsCoreAsync(printer, documentService, pages, progress, token), token);
    }

    /// <summary>
    /// Renders and prints each page one at a time via the GDI printer Device Context,
    /// disposing each bitmap immediately after use to minimise peak memory consumption.
    /// </summary>
    /// <remarks>
    /// Each page is rendered asynchronously (off the DC), then the GDI spool sequence
    /// (StartPage / StretchDIBits / EndPage) runs synchronously on the same continuation —
    /// no await crosses a GDI call, ensuring the printer DC is always driven from a
    /// consistent thread-pool context.
    /// </remarks>
    private static async Task PrintWindowsCoreAsync(
        PrinterInfo printer,
        IPdfDocumentService documentService,
        IReadOnlyList<PrintPageInfo> pages,
        IProgress<int>? progress,
        CancellationToken token)
    {
        Debug.ThrowOnUiThread();

        // CreateDCW has a friendly string overload generated by CsWin32.
        HDC hdc = PInvoke.CreateDCW(null, printer.Name, null, null);
        if (hdc.IsNull)
        {
            throw new InvalidOperationException($"Cannot create DC for printer '{printer.Name}' (Win32 error {Marshal.GetLastWin32Error()}).");
        }

        try
        {
            // StartDoc must be called from an unsafe context; delegate to a helper.
            if (StartDocUnsafe(hdc, documentService.FileName ?? "Document") <= 0)
            {
                throw new InvalidOperationException($"StartDoc failed (Win32 error {Marshal.GetLastWin32Error()}).");
            }

            try
            {
                int printerW = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.HORZRES);
                int printerH = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.VERTRES);
                int pagesProcessed = 0;

                foreach (var pageInfo in pages)
                {
                    token.ThrowIfCancellationRequested();

                    // Render the page asynchronously before touching the DC.
                    // This keeps all GDI calls (StartPage / StretchDIBits / EndPage) in the
                    // synchronous section below, with no await in between, avoiding any
                    // thread-pool thread switch while the printer DC is in use.
                    using var bitmap = await PrintServiceHelper.RenderPageToBitmapAsync(documentService, pageInfo, token)
                        .ConfigureAwait(false);

                    token.ThrowIfCancellationRequested();

                    // --- No awaits below this point until EndPage ---
                    if (PInvoke.StartPage(hdc) <= 0)
                    {
                        throw new InvalidOperationException($"StartPage failed (Win32 error {Marshal.GetLastWin32Error()}).");
                    }

                    try
                    {
                        if (bitmap is not null)
                        {
                            DrawBitmapToHdc(hdc, bitmap, printerW, printerH);
                        }
                    }
                    finally
                    {
                        _ = PInvoke.EndPage(hdc);
                    }

                    progress?.Report(++pagesProcessed);
                }
            }
            finally
            {
                _ = PInvoke.EndDoc(hdc);
            }
        }
        finally
        {
            _ = PInvoke.DeleteDC(hdc);
        }
    }

    /// <summary>
    /// Calls <c>StartDoc</c> via an <c>unsafe</c> context (required for the <c>fixed</c> pin and <c>sizeof</c>).
    /// Separated from the <c>async</c> printing method because C# forbids unsafe code in async methods.
    /// </summary>
    private static unsafe int StartDocUnsafe(HDC hdc, string docName)
    {
        fixed (char* docNamePtr = docName)
        {
            DOCINFOW docInfo;
            docInfo.cbSize = sizeof(DOCINFOW);
            docInfo.lpszDocName = docNamePtr;
            docInfo.lpszOutput = default;
            docInfo.lpszDatatype = default;
            docInfo.fwType = 0;
            return PInvoke.StartDoc(hdc, in docInfo);
        }
    }

    /// <summary>
    /// Blits <paramref name="bitmap"/> onto the printer DC using <c>StretchDIBits</c>,
    /// scaling to fill the entire printable area while preserving aspect ratio.
    /// </summary>
    private static unsafe void DrawBitmapToHdc(HDC hdc, SKBitmap bitmap, int printerW, int printerH)
    {
        // Compute destination rect preserving aspect ratio.
        float bitmapAspect = (float)bitmap.Width / bitmap.Height;
        float printerAspect = (float)printerW / printerH;

        int destW, destH, destX, destY;
        if (bitmapAspect >= printerAspect)
        {
            destW = printerW;
            destH = (int)(printerW / bitmapAspect);
            destX = 0;
            destY = (printerH - destH) / 2;
        }
        else
        {
            destH = printerH;
            destW = (int)(printerH * bitmapAspect);
            destX = (printerW - destW) / 2;
            destY = 0;
        }

        // SKBitmap with BGRA8888 matches the Windows DIB RGBQUAD memory layout.
        // Negative biHeight signals a top-down bitmap (matching SkiaSharp's origin).
        BITMAPINFO bmi = default;
        bmi.bmiHeader.biSize = (uint)sizeof(BITMAPINFOHEADER);
        bmi.bmiHeader.biWidth = bitmap.Width;
        bmi.bmiHeader.biHeight = -bitmap.Height;
        bmi.bmiHeader.biPlanes = 1;
        bmi.bmiHeader.biBitCount = 32;
        bmi.bmiHeader.biCompression = 0; // BI_RGB

        _ = PInvoke.StretchDIBits(hdc,
            destX, destY, destW, destH,
            0, 0, bitmap.Width, bitmap.Height,
            (void*)bitmap.GetPixels(),
            &bmi,
            DIB_USAGE.DIB_RGB_COLORS,
            ROP_CODE.SRCCOPY);
    }
}
