// Copyright (c) BobLd
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Threading;
using System.Threading.Tasks;
using Caly.Core.Services.Interfaces;
using Caly.Printing.Core;
using SkiaSharp;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Gdi;
using Windows.Win32.Graphics.Printing;
using Windows.Win32.Storage.Xps;
using Caly.Core;
using static Windows.Win32.Storage.Xps.PRINTER_DEVICE_CAPABILITIES;
using static Windows.Win32.Graphics.Gdi.DEVMODE_FIELD_FLAGS;

namespace Caly.Printing.Windows;

/// <summary>
/// Windows print service.
/// <para>
/// Printer discovery uses the Win32 Print Spooler via CsWin32 (<c>EnumPrinters</c>).
/// Jobs are submitted via the GDI printer-DC path (<c>CreateDC</c> / <c>StartDoc</c> /
/// <c>StartPage</c> / <c>StretchDIBits</c> / <c>EndPage</c> / <c>EndDoc</c> / <c>DeleteDC</c>).
/// </para>
/// </summary>
[SupportedOSPlatform("windows5.0")]
public sealed class WindowsPrintService : IPrintService
{
    public Task<IReadOnlyList<PrinterInfo>> GetAvailablePrintersAsync(CancellationToken token)
    {
        return Task.Run(() => GetWindowsPrintersCore(token), token);
    }

    // Minimal layout for PRINTER_INFO_4W (Level 4 enumeration — fast, local-only).
    // Level 4 is explicitly recommended for printer name enumeration (MSDN).
    // PRINTER_INFO_4W is not generated by CsWin32 due to complex struct dependencies.
    [StructLayout(LayoutKind.Sequential)]
    private unsafe struct PrinterInfo4W
    {
        public char* pPrinterName;
        public char* pServerName;
        public uint  Attributes;
    }

    private static unsafe IReadOnlyList<PrinterInfo> GetWindowsPrintersCore(CancellationToken token)
    {
        Debug.ThrowOnUiThread();

        token.ThrowIfCancellationRequested();

        try
        {
            const uint flags = 0x00000002u | 0x00000004u; // PRINTER_ENUM_LOCAL | PRINTER_ENUM_CONNECTIONS
            const uint level = 4; // PRINTER_INFO_4W — fastest for name enumeration

            // First call: get required buffer size.
            PInvoke.EnumPrinters(flags, null, level, Span<byte>.Empty, out uint needed, out _);
            if (needed == 0)
            {
                return [];
            }

            Span<byte> buffer = needed <= 1024 ? stackalloc byte[(int)needed] : new byte[needed];
            if (!PInvoke.EnumPrinters(flags, null, level, buffer, out _, out uint count))
            {
                return [];
            }

            var result = new List<PrinterInfo>();
            fixed (byte* pBuf = buffer)
            {
                var ptr = (PrinterInfo4W*)pBuf;
                for (uint i = 0; i < count; i++)
                {
                    string? name = ptr[i].pPrinterName is null ? null : new string(ptr[i].pPrinterName);
                    if (!string.IsNullOrWhiteSpace(name))
                    {
                        result.Add(new PrinterInfo(name, null));
                    }
                }
            }

            return result;
        }
        catch (Exception ex)
        {
            System.Diagnostics.Debug.WriteLine($"WindowsPrintService: EnumPrinters failed: {ex.Message}");
        }

        return [];
    }

    public Task<PrinterCapabilities> GetPrinterCapabilitiesAsync(
        PrinterInfo printer,
        CancellationToken token = default)
    {
        return Task.Run(() =>
        {
            Debug.ThrowOnUiThread();
            token.ThrowIfCancellationRequested();

            bool supportsLandscape = false;
            bool isColorDevice = false;

            try
            {
                // DC_ORIENTATION returns 90 if landscape is supported, 0 otherwise.
                int orient = PInvoke.DeviceCapabilities(printer.Name, null, DC_ORIENTATION, (DEVMODEW?)null);
                supportsLandscape = orient == 90;

                // DC_COLORDEVICE returns 1 for color, 0 for monochrome-only.
                int color = PInvoke.DeviceCapabilities(printer.Name, null, DC_COLORDEVICE, (DEVMODEW?)null);
                isColorDevice = color == 1;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(
                    $"WindowsPrintService: DeviceCapabilities failed for '{printer.Name}': {ex.Message}");
            }

            return new PrinterCapabilities(
                SupportsLandscape: supportsLandscape,
                IsColorDevice: isColorDevice,
                SupportsMonochromeDirective: isColorDevice, // every color-capable Windows driver honors DMCOLOR_MONOCHROME
                SupportedNumberUp: [1, 2, 4]);              // GDI does not expose N-up; we tile app-side
        }, token);
    }

    public Task PrintDocumentAsync(
        PrinterInfo printer,
        IPdfDocumentService documentService,
        IReadOnlyList<PrintPageInfo> pages,
        PrintSettings settings,
        IProgress<int>? progress,
        CancellationToken token)
    {
        Debug.ThrowOnUiThread();

        return Task.Run(() => PrintWindowsCoreAsync(printer, documentService, pages, settings, progress, token), token);
    }

    // dmOrientation values (wingdi.h)
    private const short DMORIENT_PORTRAIT  = 1;
    private const short DMORIENT_LANDSCAPE = 2;

    /// <summary>
    /// Opens the printer, gets a default DEVMODE, mutates orientation and color according
    /// to <paramref name="settings"/> and <paramref name="caps"/>, and round-trips it through
    /// <c>DocumentProperties</c> so the driver merges defaults. Returns the buffer (or
    /// <see langword="null"/> if any driver call fails) together with a flag indicating
    /// whether the color directive was preserved by the driver.
    /// </summary>
    private static unsafe (byte[]? Buffer, bool ColorDirectiveAccepted) BuildDevModeBuffer(
        string printerName, PrintSettings settings, PrinterCapabilities caps)
    {
        // Friendly overload returns a SafeHandle that calls ClosePrinter on Dispose.
        if (!PInvoke.OpenPrinter(printerName, out ClosePrinterSafeHandle hPrinter, null))
        {
            return (null, false);
        }

        using (hPrinter)
        {
            // Step 1: ask for the required DEVMODE buffer size (fMode = 0).
            int needed;
            fixed (char* pname = printerName)
            {
                PRINTER_HANDLE rawHandle = (PRINTER_HANDLE)hPrinter.DangerousGetHandle();

                needed = PInvoke.DocumentProperties(
                    default,
                    rawHandle,
                    new PWSTR(pname),
                    null,
                    null,
                    0);
            }

            if (needed <= 0)
            {
                return (null, false);
            }

            var buffer = new byte[needed];

            // Step 2: fill buffer with the driver's default DEVMODE (DM_OUT_BUFFER = 2).
            fixed (byte* p = buffer)
            fixed (char* pname = printerName)
            {
                PRINTER_HANDLE rawHandle = (PRINTER_HANDLE)hPrinter.DangerousGetHandle();

                int r = PInvoke.DocumentProperties(
                    default,
                    rawHandle,
                    new PWSTR(pname),
                    (DEVMODEW*)p,
                    null,
                    (uint)DM_OUT_BUFFER);

                if (r < 0)
                {
                    return (null, false);
                }
            }

            // Step 3: mutate orientation and color fields.
            fixed (byte* p = buffer)
            {
                var dm = (DEVMODEW*)p;

                short orient = settings.Orientation == PrintOrientation.Landscape
                    ? DMORIENT_LANDSCAPE
                    : DMORIENT_PORTRAIT;
                dm->Anonymous1.Anonymous1.dmOrientation = orient;
                dm->dmFields |= DM_ORIENTATION;

                if (settings.ColorMode == PrintColorMode.Monochrome && caps.SupportsMonochromeDirective)
                {
                    dm->dmColor = DEVMODE_COLOR.DMCOLOR_MONOCHROME;
                    dm->dmFields |= DM_COLOR;
                }
            }

            // Step 4: round-trip through DocumentProperties so the driver merges defaults
            // (DM_IN_BUFFER | DM_OUT_BUFFER = 8 | 2 = 10).
            fixed (byte* p = buffer)
            fixed (char* pname = printerName)
            {
                PRINTER_HANDLE rawHandle = (PRINTER_HANDLE)hPrinter.DangerousGetHandle();

                int r = PInvoke.DocumentProperties(
                    default,
                    rawHandle,
                    new PWSTR(pname),
                    (DEVMODEW*)p,
                    (DEVMODEW*)p,
                    (uint)(DM_IN_BUFFER | DM_OUT_BUFFER));
                if (r < 0)
                {
                    return (null, false);
                }
            }

            bool colorOk;
            fixed (byte* p = buffer)
            {
                var dm = (DEVMODEW*)p;
                colorOk = (dm->dmFields & DM_COLOR) != 0
                          && (settings.ColorMode != PrintColorMode.Monochrome
                              || dm->dmColor == DEVMODE_COLOR.DMCOLOR_MONOCHROME);
            }

            return (buffer, colorOk);
        }
    }

    /// <summary>
    /// Renders and prints each page one at a time via the GDI printer Device Context,
    /// disposing each bitmap immediately after use to minimise peak memory consumption.
    /// </summary>
    /// <remarks>
    /// Each page is rendered asynchronously (off the DC), then the GDI spool sequence
    /// (StartPage / StretchDIBits / EndPage) runs synchronously on the same continuation —
    /// no await crosses a GDI call, ensuring the printer DC is always driven from a
    /// consistent thread-pool context.
    /// </remarks>
    private static async Task PrintWindowsCoreAsync(
        PrinterInfo printer,
        IPdfDocumentService documentService,
        IReadOnlyList<PrintPageInfo> pages,
        PrintSettings settings,
        IProgress<int>? progress,
        CancellationToken token)
    {
        Debug.ThrowOnUiThread();

        var caps = await new WindowsPrintService().GetPrinterCapabilitiesAsync(printer, token).ConfigureAwait(false);
        var (devMode, colorDirectiveAccepted) = BuildDevModeBuffer(printer.Name, settings, caps);

        HDC hdc = CreateDCUnsafe(printer.Name, devMode);

        if (hdc.IsNull)
        {
            throw new InvalidOperationException($"Cannot create DC for printer '{printer.Name}' (Win32 error {Marshal.GetLastWin32Error()}).");
        }

        try
        {
            // StartDoc must be called from an unsafe context; delegate to a helper.
            if (StartDocUnsafe(hdc, documentService.FileName ?? "Document") <= 0)
            {
                throw new InvalidOperationException($"StartDoc failed (Win32 error {Marshal.GetLastWin32Error()}).");
            }

            try
            {
                int printerW = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.HORZRES);
                int printerH = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.VERTRES);

                int dpiX = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.LOGPIXELSX);
                int dpiY = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.LOGPIXELSY);

                int idx = 0;
                while (idx < pages.Count)
                {
                    token.ThrowIfCancellationRequested();

                    int chunkSize = Math.Min(settings.PagesPerSheet, pages.Count - idx);
                    var renderedChunk = new List<(SKBitmap Bitmap, float PdfPointsW, float PdfPointsH)>(chunkSize);

                    for (int j = 0; j < chunkSize; j++)
                    {
                        var pi = pages[idx + j];
                        var size = await documentService.GetPageSizeAsync(pi.PageNumber, token)
                            .ConfigureAwait(false);
                        var bm = await PrintServiceHelper.RenderPageToBitmapAsync(documentService, pi, token)
                            .ConfigureAwait(false);

                        if (bm is not null && size is not null)
                        {
                            if (settings.ColorMode == PrintColorMode.Monochrome && !colorDirectiveAccepted)
                            {
                                PrintServiceHelper.ConvertToGrayscaleInPlace(bm);
                            }

                            renderedChunk.Add((bm, (float)size.Value.Width, (float)size.Value.Height));
                        }
                    }

                    // Auto-orientation: flip DEVMODE based on the FIRST page in the chunk.
                    if (settings.Orientation == PrintOrientation.Auto && devMode is not null && renderedChunk.Count > 0)
                    {
                        bool wantLandscape = PrintLayout.ShouldRotateForAutoOrientation(
                            renderedChunk[0].PdfPointsW, renderedChunk[0].PdfPointsH);
                        SetDevModeOrientation(devMode, wantLandscape ? DMORIENT_LANDSCAPE : DMORIENT_PORTRAIT);
                        ResetDcWithDevMode(hdc, devMode);
                        printerW = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.HORZRES);
                        printerH = PInvoke.GetDeviceCaps(hdc, GET_DEVICE_CAPS_INDEX.VERTRES);
                    }

                    if (PInvoke.StartPage(hdc) <= 0)
                    {
                        foreach (var (bm, _, _) in renderedChunk)
                        {
                            bm.Dispose();
                        }

                        throw new InvalidOperationException($"StartPage failed (Win32 error {Marshal.GetLastWin32Error()}).");
                    }

                    try
                    {
                        DrawSheetToHdc(hdc, renderedChunk, settings, printerW, printerH, dpiX, dpiY);
                    }
                    finally
                    {
                        _ = PInvoke.EndPage(hdc);
                        foreach (var (bm, _, _) in renderedChunk)
                        {
                            bm.Dispose();
                        }
                    }

                    idx += chunkSize;
                    progress?.Report(idx);
                }
            }
            finally
            {
                _ = PInvoke.EndDoc(hdc);
            }
        }
        finally
        {
            _ = PInvoke.DeleteDC(hdc);
        }
    }

    /// <summary>
    /// Calls the raw <c>CreateDCW</c> pointer overload so that the full DEVMODE buffer
    /// (public fields + private driver data) is passed intact.
    /// Separated from the <c>async</c> printing method because C# forbids unsafe code in
    /// async methods.
    /// </summary>
    private static unsafe HDC CreateDCUnsafe(string printerName, byte[]? devMode)
    {
        fixed (char* pname = printerName)
        fixed (byte* pdm = devMode) // pdm is null when devMode is null
        {
            return PInvoke.CreateDCW(
                default,    // pwszDriver = null (ignored for printers)
                new PCWSTR(pname),
                default,    // pszPort = null
                (DEVMODEW*)pdm);    // null when devMode is null — uses driver default
        }
    }

    /// <summary>
    /// Calls <c>StartDoc</c> via an <c>unsafe</c> context (required for the <c>fixed</c> pin and <c>sizeof</c>).
    /// Separated from the <c>async</c> printing method because C# forbids unsafe code in async methods.
    /// </summary>
    private static unsafe int StartDocUnsafe(HDC hdc, string docName)
    {
        fixed (char* docNamePtr = docName)
        {
            DOCINFOW docInfo;
            docInfo.cbSize = sizeof(DOCINFOW);
            docInfo.lpszDocName = docNamePtr;
            docInfo.lpszOutput = default;
            docInfo.lpszDatatype = default;
            docInfo.fwType = 0;
            return PInvoke.StartDoc(hdc, in docInfo);
        }
    }

    /// <summary>
    /// Mutates the <c>dmOrientation</c> field in a raw DEVMODE byte buffer in-place.
    /// </summary>
    private static unsafe void SetDevModeOrientation(byte[] buffer, short orientation)
    {
        fixed (byte* p = buffer)
        {
            var dm = (DEVMODEW*)p;
            dm->Anonymous1.Anonymous1.dmOrientation = orientation;
            dm->dmFields |= DM_ORIENTATION;
        }
    }

    /// <summary>
    /// Calls <c>ResetDCW</c> with the supplied DEVMODE buffer to apply orientation or
    /// other setting changes to an already-open printer DC.
    /// Separated from the <c>async</c> printing method because C# forbids unsafe code in
    /// async methods.
    /// </summary>
    private static unsafe void ResetDcWithDevMode(HDC hdc, byte[] buffer)
    {
        fixed (byte* p = buffer)
        {
            _ = PInvoke.ResetDCW(hdc, (DEVMODEW*)p);
        }
    }

    /// <summary>
    /// Draws zero-or-more page bitmaps onto the printer DC using the cell layout from
    /// <see cref="PrintLayout.ComputeCells"/>. Each cell is sized according to <paramref name="settings"/>'s
    /// fit mode. Used inside a single StartPage / EndPage block.
    /// </summary>
    private static unsafe void DrawSheetToHdc(
        HDC hdc,
        IReadOnlyList<(SKBitmap Bitmap, float PdfPointsW, float PdfPointsH)> sourcePages,
        PrintSettings settings,
        int printerW,
        int printerH,
        int dpiX,
        int dpiY)
    {
        var cells = PrintLayout.ComputeCells(printerW, printerH, settings.PagesPerSheet);

        for (int i = 0; i < sourcePages.Count && i < cells.Count; i++)
        {
            var (bitmap, ppW, ppH) = sourcePages[i];
            if (bitmap is null)
            {
                continue;
            }

            // 2-up rotation note: cells are split along the longer paper edge. On portrait
            // paper, 2-up stacks pages top/bottom; on landscape paper, side-by-side. This
            // is a deliberate v1 simplification — Adobe-style per-page 90° rotation can be
            // added later. The unit tests in PrintLayoutCellsTests lock in the cell behavior.

            var dest = PrintLayout.ComputeDestRect(
                cells[i], bitmap.Width, bitmap.Height, ppW, ppH, dpiX, dpiY,
                settings.FitMode, settings.CustomScalePercent);

            BITMAPINFO bmi = default;
            bmi.bmiHeader.biSize = (uint)sizeof(BITMAPINFOHEADER);
            bmi.bmiHeader.biWidth = bitmap.Width;
            bmi.bmiHeader.biHeight = -bitmap.Height;
            bmi.bmiHeader.biPlanes = 1;
            bmi.bmiHeader.biBitCount = 32;
            bmi.bmiHeader.biCompression = 0;

            _ = PInvoke.StretchDIBits(hdc,
                dest.X, dest.Y, dest.Width, dest.Height,
                0, 0, bitmap.Width, bitmap.Height,
                (void*)bitmap.GetPixels(),
                &bmi,
                DIB_USAGE.DIB_RGB_COLORS,
                ROP_CODE.SRCCOPY);
        }
    }
}
