using Caly.Pdf.Models;
using UglyToad.PdfPig.Core;
using UglyToad.PdfPig.DocumentLayoutAnalysis;

namespace Caly.Pdf.Layout;

/*
 * From PdfPig
 */

/// <summary>
/// The Document Spectrum (Docstrum) algorithm is a bottom-up page segmentation technique based on nearest-neighbourhood
/// clustering of connected components extracted from the document.
/// This implementation leverages bounding boxes and does not exactly replicate the original algorithm.
/// <para>See 'The document spectrum for page layout analysis.' by L. O'Gorman.</para>
/// </summary>
public sealed class CalyDocstrum
{
    private readonly CalyDocstrumOptions options;

    /// <summary>
    /// Create an instance of Docstrum for bounding boxes page segmenter, <see cref="CalyDocstrum"/>.
    /// </summary>
    public static readonly CalyDocstrum Instance = new CalyDocstrum();

    /// <summary>
    /// Create an instance of Docstrum for bounding boxes page segmenter using default options values.
    /// </summary>
    public CalyDocstrum() : this(new CalyDocstrumOptions())
    {
    }

    /// <summary>
    /// Create an instance of Docstrum for bounding boxes page segmenter using options values.
    /// </summary>
    /// <param name="options">The <see cref="CalyDocstrumOptions"/> to use.</param>
    /// <exception cref="ArgumentException"></exception>
    public CalyDocstrum(CalyDocstrumOptions options)
    {
        this.options = options ?? throw new ArgumentNullException(nameof(options));
    }

    /// <summary>
    /// Get the blocks.
    /// </summary>
    /// /// <param name="words">The page's words to segment into <see cref="PdfTextBlock"/>s.</param>
    /// <param name="cancellationToken"></param>
    /// <returns>The <see cref="PdfTextBlock"/>s generated by the document spectrum method.</returns>
    public IReadOnlyList<PdfTextBlock> GetBlocks(IEnumerable<PdfWord> words, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        
        if (words is null)
        {
            return Array.Empty<PdfTextBlock>();
        }

        PdfWord[]? array = words?.Where(w => !w.Value.AsSpan().IsEmpty).ToArray();

        if (array is null || array.Length == 0)
        {
            return [];
        }

        var parallelOptions = new ParallelOptions()
        {
            MaxDegreeOfParallelism = options.MaxDegreeOfParallelism,
            CancellationToken = cancellationToken
        };

        return GetBlocks(array,
            options.WithinLineBounds, options.WithinLineMultiplier, options.WithinLineBinSize,
            options.BetweenLineBounds, options.BetweenLineMultiplier, options.BetweenLineBinSize,
            options.AngularDifferenceBounds,
            options.Epsilon,
            parallelOptions);
    }

    /// <summary>
    /// Get the blocks. See original paper for more information.
    /// </summary>
    /// <param name="words">The words to segment into <see cref="PdfTextBlock"/>s.</param>
    /// <param name="wlBounds">Angle bounds for words to be considered as neighbours on the same line.</param>
    /// <param name="wlMultiplier">Multiplier that gives the maximum euclidian distance between words for building lines.
    /// Maximum distance will be this number times the within-line distance found by the analysis.</param>
    /// <param name="wlBinSize">The bin size used when building the within-line distances distribution.</param>
    /// <param name="blBounds">Angle bounds for words to be considered as neighbours on separate lines.</param>
    /// <param name="blMultiplier">Multiplier that gives the maximum perpendicular distance between
    /// text lines for blocking. Maximum distance will be this number times the between-line
    /// distance found by the analysis.</param>
    /// <param name="blBinSize">The bin size used when building the between-line distances distribution.</param>
    /// <param name="angularDifferenceBounds">The angular difference bounds between two lines to be considered in the same block. This defines if two lines are parallel enough.</param>
    /// <param name="epsilon">Precision when testing equalities.</param>
    /// <param name="parallelOptions">A <see cref="ParallelOptions">ParallelOptions</see>
    /// instance that configures the behavior of this operation.</param>/// If it is -1, there is no limit on the number of concurrently running operations.</para></param>
    /// <returns>The <see cref="PdfTextBlock"/>s generated by the document spectrum method.</returns>
    private static IReadOnlyList<PdfTextBlock> GetBlocks(IReadOnlyList<PdfWord> words,
        AngleBounds wlBounds, float wlMultiplier, int wlBinSize,
        AngleBounds blBounds, float blMultiplier, int blBinSize,
        AngleBounds angularDifferenceBounds,
        float epsilon,
        ParallelOptions parallelOptions)
    {
        parallelOptions.CancellationToken.ThrowIfCancellationRequested();

        // 1. Estimate within line and between line spacing
        if (!GetSpacingEstimation(words, wlBounds, wlBinSize, blBounds, blBinSize,
            parallelOptions, out float withinLineDistance, out float betweenLineDistance))
        {
            if (float.IsNaN(withinLineDistance))
            {
                withinLineDistance = 0;
            }

            if (float.IsNaN(betweenLineDistance))
            {
                betweenLineDistance = 0;
            }
        }

        // 2. Determination of Text Lines
        float maxWithinLineDistance = wlMultiplier * withinLineDistance;
        var lines = GetLines(words, maxWithinLineDistance, wlBounds, parallelOptions).ToArray();

        // 3. Structural Block Determination
        float maxBetweenLineDistance = blMultiplier * betweenLineDistance;
        return GetStructuralBlocks(lines, maxBetweenLineDistance, angularDifferenceBounds, epsilon, parallelOptions).ToArray();
    }

    #region Spacing Estimation
    /// <summary>
    /// Estimation of within-line and between-line spacing.
    /// <para>This is the Docstrum algorithm's 1st step.</para>
    /// </summary>
    /// <param name="words">The list of words.</param>
    /// <param name="wlBounds">Angle bounds for words to be considered as neighbours on the same line.</param>
    /// <param name="wlBinSize">The bin size used when building the within-line distances distribution.</param>
    /// <param name="blBounds">Angle bounds for words to be considered as neighbours on separate lines.</param>
    /// <param name="blBinSize">The bin size used when building the between-line distances distribution.</param>
    /// <param name="parallelOptions">A <see cref="ParallelOptions">ParallelOptions</see>
    /// instance that configures the behavior of this operation.</param>
    /// <param name="withinLineDistance">The estimated within-line distance. Computed as the average peak value of distribution.</param>
    /// <param name="betweenLineDistance">The estimated between-line distance. Computed as the average peak value of distribution.</param>
    /// <returns>False if either 'withinLineDistance' or 'betweenLineDistance' is <see cref="float.NaN"/>.</returns>
    public static bool GetSpacingEstimation(IReadOnlyList<PdfWord> words,
        AngleBounds wlBounds, int wlBinSize,
        AngleBounds blBounds, int blBinSize,
        ParallelOptions parallelOptions,
        out float withinLineDistance, out float betweenLineDistance)
    {
        var withinLineDistList = new List<float>();
        var betweenLineDistList = new List<float>();

        // 1. Estimate within line and between line spacing
        CalyKdTree<PdfWord> kdTreeBottomLeft = new CalyKdTree<PdfWord>(words, w => w.BoundingBox.BottomLeft);

        Parallel.For(0, words.Count, parallelOptions,
            () => (wl: new List<float>(), bl: new List<float>()),
            (i, _, local) =>
            {
                var word = words[i];

                // Within-line distance
                // 1.1.1 Find the 2 closest neighbours words to the candidate, using euclidean distance.
                foreach (var n in kdTreeBottomLeft.FindNearestNeighbours(word, 2, w => w.BoundingBox.BottomRight, CalyDistances.Euclidean))
                {
                    // 1.1.2 Check if the neighbour word is within the angle of the candidate
                    if (wlBounds.Contains(AngleWL(word, n.Item1)))
                    {
                        local.wl.Add(CalyDistances.Euclidean(word.BoundingBox.BottomRight, n.Item1.BoundingBox.BottomLeft));
                    }
                }

                // Between-line distance
                // 1.2.1 Find the 2 closest neighbours words to the candidate, using euclidean distance.
                foreach (var n in kdTreeBottomLeft.FindNearestNeighbours(word, 2, w => w.BoundingBox.TopLeft, CalyDistances.Euclidean))
                {
                    // 1.2.2 Check if the candidate words is within the angle
                    var angle = AngleBL(word, n.Item1);
                    if (blBounds.Contains(angle))
                    {
                        // 1.2.3 Compute the vertical (between-line) distance between the candidate
                        // and the neighbour and add it to the between-line distances list
                        float hypotenuse = CalyDistances.Euclidean(word.BoundingBox.Centroid, n.Item1.BoundingBox.Centroid);

                        // Angle is kept within [-90, 90]
                        if (angle > 90)
                        {
                            angle -= 180;
                        }

                        var dist = MathF.Abs(hypotenuse * MathF.Cos((90 - angle) * MathF.PI / 180))
                                   - (float)word.BoundingBox.Height / 2.0f - (float)n.Item1.BoundingBox.Height / 2.0f;

                        // The perpendicular distance can be negative because of the subtractions.
                        // Could occur when words are overlapping, we ignore that.
                        if (dist >= 0)
                        {
                            local.bl.Add(dist);
                        }
                    }
                }

                return local;
            },
            local =>
            {
                lock (withinLineDistList)
                {
                    withinLineDistList.AddRange(local.wl);
                }
                lock (betweenLineDistList)
                {
                    betweenLineDistList.AddRange(local.bl);
                }
            });

        // Compute average peak value of distribution
        float? withinLinePeak = GetPeakAverageDistance(withinLineDistList, wlBinSize);
        float? betweenLinePeak = GetPeakAverageDistance(betweenLineDistList, blBinSize);

        withinLineDistance = withinLinePeak ?? float.NaN;
        betweenLineDistance = betweenLinePeak ?? float.NaN;

        return withinLinePeak.HasValue && betweenLinePeak.HasValue;
    }

    /// <summary>
    /// Get the average distance value of the peak bucket of the histogram.
    /// </summary>
    /// <param name="distances">The set of distances to average.</param>
    /// <param name="binLength"></param>
    private static float? GetPeakAverageDistance(List<float> distances, int binLength = 1)
    {
        if (distances.Count == 0)
        {
            return null;
        }

        if (binLength <= 0)
        {
            throw new ArgumentException("DocstrumBoundingBoxes: the bin length must be positive when computing peak average distance.", nameof(binLength));
        }

        float maxDbl = distances[0];
        for (int i = 1; i < distances.Count; i++)
        {
            if (distances[i] > maxDbl)
            {
                maxDbl = distances[i];
            }
        }

        maxDbl = MathF.Ceiling(maxDbl);
        if (maxDbl > int.MaxValue)
        {
            throw new OverflowException($"Error while casting maximum distance of {maxDbl} to integer.");
        }

        int max = (int)maxDbl;
        if (max == 0)
        {
            max = binLength;
        }
        else
        {
            binLength = binLength > max ? max : binLength;
        }

        int binCount = (int)Math.Ceiling(max / (double)binLength) + 1;
        var bins = new List<float>[binCount];
        for (int i = 0; i < binCount; i++)
        {
            bins[i] = new List<float>();
        }

        for (int i = 0; i < distances.Count; i++)
        {
            var distance = distances[i];
            int bin = (int)Math.Floor(distance / binLength);
            if (bin < 0)
            {
                throw new ArgumentOutOfRangeException(nameof(bin), "DocstrumBoundingBoxes: Negative distance found while commputing peak average distance.");
            }
            if (bin >= binCount)
            {
                bin = binCount - 1;
            }
            bins[bin].Add(distance);
        }

        List<float> best = null;
        for (int i = 0; i < binCount; i++)
        {
            var bin = bins[i];
            if (best is null || bin.Count > best.Count)
            {
                best = bin;
            }
        }

        if (best == null || best.Count == 0)
        {
            return null;
        }

        float sum = 0;
        for (int i = 0; i < best.Count; i++)
        {
            sum += best[i];
        }
        return sum / best.Count;
    }
    #endregion

    #region Text Lines
    /// <summary>
    /// Get the <see cref="PdfTextLine"/>s by grouping words using nearest neighbours.
    /// <para>This is the Docstrum algorithm's 2nd step.</para>
    /// </summary>
    /// <param name="words">The words to segment into <see cref="PdfTextLine"/>s.</param>
    /// <param name="maxWLDistance">The maximum within-line distance. Computed as the estimated within-line spacing times the within-line multiplier in the default implementation.</param>
    /// <param name="wlBounds">Angle bounds for words to be considered as neighbours on the same line.</param>
    /// <param name="parallelOptions">A <see cref="ParallelOptions">ParallelOptions</see>
    /// instance that configures the behavior of this operation.</param>
    /// <returns>The <see cref="PdfTextLine"/>s built.</returns>
    public static IEnumerable<PdfTextLine> GetLines(IReadOnlyList<PdfWord> words, float maxWLDistance, AngleBounds wlBounds, ParallelOptions parallelOptions)
    {
        var groupedWords = CalyClustering.NearestNeighbours(words,
            2,
            CalyDistances.Euclidean,
            (_, __) => maxWLDistance,
            pivot => pivot.BoundingBox.BottomRight,
            candidate => candidate.BoundingBox.BottomLeft,
            _ => true,
            (pivot, candidate) => wlBounds.Contains(AngleWL(pivot, candidate)),
            parallelOptions);

        foreach (var gr in groupedWords)
        {
            yield return new PdfTextLine(gr.OrderByReadingOrder().ToArray());
        }
    }

    /// <summary>
    /// Helper function to compute the within line angle between the pivot's bottom
    /// right and the candidate's bottom left points, taking in account the pivot's rotation.
    /// <para>-90 ≤ θ ≤ 90.</para>
    /// </summary>
    private static float AngleWL(PdfWord pivot, PdfWord candidate)
    {
        PdfPoint pivotBottomRight = pivot.BoundingBox.BottomRight;
        PdfPoint candidateBottomLeft = candidate.BoundingBox.BottomLeft;

        if (pivotBottomRight.Equals(candidateBottomLeft))
        {
            return 0;
        }

        float angle = CalyDistances.BoundAngle180(CalyDistances.Angle(in pivotBottomRight, in candidateBottomLeft) - (float)pivot.BoundingBox.Rotation);

        // Angle is kept within [-90;90] degree to handle overlapping words
        if (angle > 90)
        {
            angle -= 180;
        }
        else if (angle < -90)
        {
            angle += 180;
        }

        return angle;
    }
    #endregion

    #region Blocking
    /// <summary>
    /// Get the <see cref="PdfTextBlock"/>s.
    /// <para>This is the Docstrum algorithm's 3rd and final step.</para>
    /// <para>
    /// Method: We want to measure the distance between two lines using the following method:
    /// <br>- We check if two lines are overlapping horizontally and compute the perpendicular distance.</br>
    /// <br>- We check if the angle between the two line is within 'angularDifference'.</br>
    /// <br>- If the two lines are not overlapping or the angle is too wide, the distance is set to the infinity.</br>
    /// <para>If two text lines are approximately parallel, close in perpendicular distance, and they either overlap to some specified degree or are separated by only a small distance in parallel distance, then they are said to meet the criteria to belong to the same structural block.</para>
    /// </para>
    /// </summary>
    /// <param name="lines">The lines to segment into <see cref="PdfTextBlock"/>s.</param>
    /// <param name="maxBLDistance">The maximum between-line distance. Computed as the estimated between-line spacing times the between-line multiplier in the default implementation.</param>
    /// <param name="angularDifferenceBounds">The angular difference bounds between two lines to be considered in the same block. This defines if two lines are parallel enough.</param>
    /// <param name="epsilon">Precision when testing equalities.</param>
    /// <param name="parallelOptions">A <see cref="ParallelOptions">ParallelOptions</see>
    /// instance that configures the behavior of this operation.</param>
    /// <returns>The <see cref="PdfTextBlock"/>s built.</returns>
    public static IEnumerable<PdfTextBlock> GetStructuralBlocks(IReadOnlyList<PdfTextLine> lines,
        float maxBLDistance, AngleBounds angularDifferenceBounds, float epsilon, ParallelOptions parallelOptions)
    {
        /******************************************************************************************************
         * We want to measure the distance between two lines using the following method:
         *  We check if two lines are overlapping horizontally and compute the perpendicular distance.
         *  We check if the angle between the two line is within 'angularDifference'.
         *  If the two lines are not overlapping or the angle is too wide, the distance is set to the infinity.
         *  
         *  If two text lines are approximately parallel, close in perpendicular distance, and they either 
         *  overlap to some specified degree or are separated by only a small distance in parallel distance, 
         *  then they are said to meet the criteria to belong to the same structural block.
         ******************************************************************************************************/

        var groupedLines = CalyClustering.NearestNeighbours(
            lines,
            (l1, l2) => PerpendicularOverlappingDistance(in l1, in l2, ref angularDifferenceBounds, epsilon),
            (_, __) => maxBLDistance,
            pivot => new PdfLine(pivot.BoundingBox.BottomLeft, pivot.BoundingBox.BottomRight),
            candidate => new PdfLine(candidate.BoundingBox.TopLeft, candidate.BoundingBox.TopRight),
            _ => true,
            (_, __) => true,
            parallelOptions).ToArray();

        foreach (var g in groupedLines)
        {
            yield return new PdfTextBlock(g.OrderByReadingOrder().ToArray());
        }
    }

    /// <summary>
    /// Perpendicular overlapping distance.
    /// </summary>
    /// <param name="line1"></param>
    /// <param name="line2"></param>
    /// <param name="angularDifferenceBounds"></param>
    /// <param name="epsilon"></param>
    private static float PerpendicularOverlappingDistance(ref readonly PdfLine line1, ref readonly PdfLine line2, ref readonly AngleBounds angularDifferenceBounds, float epsilon)
    {
        if (GetStructuralBlockingParameters(in line1, in line2, epsilon, out float theta, out _, out float ed))
        {
            // Angle is kept within [-90;90]
            if (theta > 90)
            {
                theta -= 180;
            }
            else if (theta < -90)
            {
                theta += 180;
            }

            if (!angularDifferenceBounds.Contains(theta))
            {
                // exclude because not parallel enough
                return float.PositiveInfinity;
            }

            return MathF.Abs(ed);
        }
        else
        {
            // nonoverlapped
            return float.PositiveInfinity;
        }
    }

    /// <summary>
    /// Get the structural blocking parameters.
    /// </summary>
    /// <param name="i"></param>
    /// <param name="j"></param>
    /// <param name="epsilon"></param>
    /// <param name="angularDifference">The angle between the 2 lines.<para>-180 ≤ θ ≤ 180</para></param>
    /// <param name="normalisedOverlap">Overlap of segment i onto j. Positive value if overlapped, negative value if nonoverlapped.<para>[-1, 1]?</para></param>
    /// <param name="perpendicularDistance">Signed perpendicular distance.</param>
    /// <returns>Return true if overlapped, false if nonoverlapped.</returns>
    public static bool GetStructuralBlockingParameters(in PdfLine i, in PdfLine j, float epsilon,
        out float angularDifference, out float normalisedOverlap, out float perpendicularDistance)
    {
        if (AlmostEquals(in i, in j, epsilon))
        {
            angularDifference = 0;
            normalisedOverlap = 1;
            perpendicularDistance = 0;
            return true;
        }

        PdfPoint j1 = j.Point1;
        PdfPoint j2 = j.Point2;

        float dXi = (float)i.Point2.X - (float)i.Point1.X;
        float dYi = (float)i.Point2.Y - (float)i.Point1.Y;
        float dXj = (float)j2.X - (float)j1.X;
        float dYj = (float)j2.Y - (float)j1.Y;

        angularDifference = CalyDistances.BoundAngle180((MathF.Atan2(dYj, dXj) - MathF.Atan2(dYi, dXi)) * 180 / MathF.PI);

        PdfPoint? Aj = GetTranslatedPoint((float)i.Point1.X, (float)i.Point1.Y, (float)j1.X, (float)j1.Y, dXi, dYi, dXj, dYj, epsilon);
        PdfPoint? Bj = GetTranslatedPoint((float)i.Point2.X, (float)i.Point2.Y, (float)j2.X, (float)j2.Y, dXi, dYi, dXj, dYj, epsilon);

        if (!Aj.HasValue || !Bj.HasValue)
        {
            // Might happen because lines are perpendicular
            // or have too small lengths
            normalisedOverlap = float.NaN;
            perpendicularDistance = float.NaN;
            return false;
        }

        PdfPoint ajv = Aj.Value;
        PdfPoint bjv = Bj.Value;

        // Get middle points
        Span<PdfPoint> ps = stackalloc PdfPoint[] { j1, j2, ajv, bjv };

        if (dXj != 0)
        {
            ps.Sort((p1, p2) =>
            {
                int comp = p1.X.CompareTo(p2.X);
                return comp == 0 ? p1.Y.CompareTo(p2.Y) : comp;
            });
        }
        else if (dYj != 0)
        {
            ps.Sort((p1, p2) => p1.Y.CompareTo(p2.Y));
        }

        ref readonly PdfPoint Cj = ref ps[1];
        ref readonly PdfPoint Dj = ref ps[2];

        // Cj and Dj should be contained within both j and [Aj,Bj] if overlapped
        bool overlap = !(!PointInLine(in j1, in j2, in Cj) || !PointInLine(in j1, in j2, in Dj) ||
                         !PointInLine(in ajv, in bjv, in Cj) || !PointInLine(in ajv, in bjv, in Dj));

        float pj = CalyDistances.Euclidean(Cj, Dj);

        normalisedOverlap = (overlap ? pj : -pj) / (float)j.Length;

        float xMj = ((float)Cj.X + (float)Dj.X) / 2.0f;
        float yMj = ((float)Cj.Y + (float)Dj.Y) / 2.0f;

        if (!dXi.AlmostEqualsToZero(epsilon) && !dYi.AlmostEqualsToZero(epsilon))
        {
            perpendicularDistance = ((xMj - (float)i.Point1.X) - (yMj - (float)i.Point1.Y) * dXi / dYi) / MathF.Sqrt(dXi * dXi / (dYi * dYi) + 1);
        }
        else if (dXi.AlmostEqualsToZero(epsilon))
        {
            perpendicularDistance = xMj - (float)i.Point1.X;
        }
        else
        {
            perpendicularDistance = yMj - (float)i.Point1.Y;
        }

        return overlap;
    }

    private static PdfPoint? GetTranslatedPoint(float xPi, float yPi, float xPj, float yPj, float dXi, float dYi, float dXj, float dYj, float epsilon)
    {
        float dYidYj = dYi * dYj;
        float dXidXj = dXi * dXj;
        float denominator = dYidYj + dXidXj;

        if (denominator.AlmostEqualsToZero(epsilon))
        {
            // The denominator is 0 when translating points, meaning the lines are perpendicular.
            return null;
        }

        float xAj;
        float yAj;

        if (!dXj.AlmostEqualsToZero(epsilon)) // dXj != 0
        {
            xAj = (xPi * dXidXj + xPj * dYidYj + dXj * dYi * (yPi - yPj)) / denominator;
            yAj = dYj / dXj * (xAj - xPj) + yPj;
        }
        else // If dXj = 0, then yAj is calculated first, and xAj is calculated from that.
        {
            yAj = (yPi * dYidYj + yPj * dXidXj + dYj * dXi * (xPi - xPj)) / denominator;
            xAj = xPj;
        }

        return new PdfPoint(xAj, yAj);
    }

    /// <summary>
    /// Helper function to check if the point belongs to the line./>
    /// </summary>
    /// <param name="pl1">Line's first point.</param>
    /// <param name="pl2">Line's second point.</param>
    /// <param name="point">The point to check.</param>
    private static bool PointInLine(in PdfPoint pl1, in PdfPoint pl2, in PdfPoint point)
    {
        // /!\ Assuming the points are aligned (be careful)
        float ax = (float)point.X - (float)pl1.X;
        float ay = (float)point.Y - (float)pl1.Y;
        float bx = (float)pl2.X - (float)pl1.X;
        float by = (float)pl2.Y - (float)pl1.Y;

        float dotProd1 = ax * bx + ay * by;
        return dotProd1 >= 0 && dotProd1 <= (bx * bx + by * by);
    }

    /// <summary>
    /// Helper function to check if 2 lines are equal.
    /// </summary>
    private static bool AlmostEquals(in PdfLine line1, in PdfLine line2, float epsilon)
    {
        return (line1.Point1.X - line2.Point1.X).AlmostEqualsToZero(epsilon) &&
               (line1.Point1.Y - line2.Point1.Y).AlmostEqualsToZero(epsilon) &&
               (line1.Point2.X - line2.Point2.X).AlmostEqualsToZero(epsilon) &&
               (line1.Point2.Y - line2.Point2.Y).AlmostEqualsToZero(epsilon);
    }

    /// <summary>
    /// Helper function to compute the between line angle between the pivot's
    /// and the candidate's centroid points, taking in account the pivot's rotation.
    /// <para>0 ≤ θ ≤ 180.</para>
    /// </summary>
    private static float AngleBL(PdfWord pivot, PdfWord candidate)
    {
        var angle = CalyDistances.BoundAngle180(CalyDistances.Angle(pivot.BoundingBox.Centroid, candidate.BoundingBox.Centroid) - (float)pivot.BoundingBox.Rotation);

        // Angle is kept within [0, 180] for the check
        if (angle < 0)
        {
            angle += 180;
        }

        return angle;
    }
    #endregion

    /// <summary>
    /// The bounds for the angle between two words for them to have a certain type of relationship.
    /// </summary>
    public readonly struct AngleBounds
    {
        /// <summary>
        /// The lower bound in degrees.
        /// </summary>
        public float Lower { get; }

        /// <summary>
        /// The upper bound in degrees.
        /// </summary>
        public float Upper { get; }

        /// <summary>
        /// Create a new <see cref="AngleBounds"/>.
        /// </summary>
        public AngleBounds(float lowerBound, float upperBound)
        {
            if (lowerBound >= upperBound)
            {
                throw new ArgumentException("The lower bound should be smaller than the upper bound.");
            }

            Lower = lowerBound;
            Upper = upperBound;
        }

        /// <summary>
        /// Whether the bounds contain the angle.
        /// </summary>
        public bool Contains(float angle)
        {
            return angle >= Lower && angle <= Upper;
        }
    }

    /// <summary>
    /// Docstrum bounding boxes page segmenter options.
    /// </summary>
    public sealed class CalyDocstrumOptions // : IPageSegmenterOptions
    {
        /// <summary>
        /// <inheritdoc/>
        /// Default value is -1.
        /// </summary>
        public int MaxDegreeOfParallelism { get; init; } = -1;

        /// <summary>
        /// Precision when testing equalities.
        /// <para>Default value is 1e-3.</para>
        /// </summary>
        public float Epsilon { get; init; } = 1e-3f;

        /// <summary>
        /// Angle bounds for words to be considered as neighbours on the same line.
        /// <para>Default value is -30 ≤ θ ≤ 30.</para>
        /// </summary>
        public AngleBounds WithinLineBounds { get; init; } = new AngleBounds(-30, 30);

        /// <summary>
        /// Multiplier that gives the maximum euclidean distance between
        /// words for building lines. Maximum distance will be this number times the within-line
        /// distance found by the analysis.
        /// <para>Default value is 3.</para>
        /// </summary>
        public float WithinLineMultiplier { get; init; } = 3.0f;

        /// <summary>
        /// The bin size used when building the within-line distances distribution.
        /// <para>Default value is 10.</para>
        /// </summary>
        public int WithinLineBinSize { get; init; } = 10;

        /// <summary>
        /// Angle bounds for words to be considered as neighbours on separate lines.
        /// <para>Default value is 45 ≤ θ ≤ 135.</para>
        /// </summary>
        public AngleBounds BetweenLineBounds { get; init; } = new AngleBounds(45, 135);

        /// <summary>
        /// Multiplier that gives the maximum perpendicular distance between
        /// text lines for blocking. Maximum distance will be this number times the between-line
        /// distance found by the analysis.
        /// <para>Default value is 1.3.</para>
        /// </summary>
        public float BetweenLineMultiplier { get; init; } = 1.3f;

        /// <summary>
        /// The bin size used when building the between-line distances distribution.
        /// <para>Default value is 10.</para>
        /// </summary>
        public int BetweenLineBinSize { get; init; } = 10;

        /// <summary>
        /// The angular difference bounds between two lines to be considered in the same block.
        /// This defines if two lines are parallel enough.
        /// <para>Default value is -30 ≤ θ ≤ 30.</para>
        /// </summary>
        public AngleBounds AngularDifferenceBounds { get; init; } = new AngleBounds(-30, 30);
    }
}
